name: Mirroring repository

on: [push]

env:
    MIRROR_URL: https://github.com/EpitechPGEPromo2029/B-DOP-200-PAR-2-1-bschocolatine-nicky.truong.git

jobs:
    Mirroring_repository:
        name: Mirroring repository
        runs-on: ubuntu-latest
        steps:
            - uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url: $MIRROR_URL