name: Mirroring repository

on: [push]

env:
    MIRROR_URL: EpitechPGEPromo2029/B-DOP-200-PAR-2-1-bschocolatine-nicky.truong.git

jobs:
    Mirroring_repository:
        name: Mirroring repository
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url:
                    ${{ env.MIRROR_URL }}
                ssh_private_key:
                    ${{ secrets.GITHUB_TOKEN }}
                ssh_username:
                    ${{ secrets.GITHUB_TOKEN }}