name: Mirroring repository

on: [push]

jobs:
    Mirroring_repository:
        name: Mirroring repository
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url:
                    ssh://git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-bschocolatine-nicky.truong.git
                ssh_private_key:
                    ${{ secrets.BS_CHOCOLATINE }}
                ssh_username:
                    ${{ secrets.BS_CHOCOLATINE }}